name: movie_search_app
description: Your project description

environment:
  sdk: '^3.5.0'

  

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6 # For API calls
  provider: ^6.1.2 # For state management (bonus)
  google_fonts: ^2.3.2 # For Montserrat typography
